### ISSUE TITLE
MainWindow object thas no attribute setCentralWidget

### ISSUE THREAD

**Issue by wa1ker38552** [zhiyiYo/PyQt-Frameless-Window#169]
```py
class MainWindow(FramelessWindow):
    def __init__(self):
        super().__init__()
        self.central_widget = QWidget()
        self.setCentralWidget(self.central_widget)

app = QApplication(sys.argv)
window = MainWindow()
window.show()
sys.exit(app.exec_())
```

```
Traceback (most recent call last):
  File "C:\Users\walke\Downloads\VSCode\multi instance\gui.py", line 151, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\walke\Downloads\VSCode\multi instance\gui.py", line 107, in __init__
    self.setCentralWidget(self.central_widget)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'setCentralWidget'. Did you mean: 'central_widget'?
```

Tried this as well and it didn't work `class MainWindow(FramelessWindow, QMainWindow):`
If I removed FramelessWindow and only have QMainWindow it works.

**Comment by zhiyiYo** [comment]
Check the examples
