### ISSUE TITLE
Mac-PyQt6使用报错

### ISSUE THREAD

**Issue by AuroraZiling** [zhiyiYo/PyQt-Frameless-Window#69]
**报错信息**
```python
Traceback (most recent call last):
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets-PyQt6/examples/navigation2/demo.py", line 7, in <module>
    from qfluentwidgets import (NavigationInterface, NavigationItemPostion, NavigationWidget, MessageBox,
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets-PyQt6/qfluentwidgets/__init__.py", line 17, in <module>
    from .components import *
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets-PyQt6/qfluentwidgets/components/__init__.py", line 1, in <module>
    from .dialog_box import *
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets-PyQt6/qfluentwidgets/components/dialog_box/__init__.py", line 1, in <module>
    from .color_dialog import ColorDialog
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets-PyQt6/qfluentwidgets/components/dialog_box/color_dialog.py", line 8, in <module>
    from ..widgets import Slider, ScrollArea, PushButton, PrimaryPushButton
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets-PyQt6/qfluentwidgets/components/widgets/__init__.py", line 1, in <module>
    from .combo_box import ComboBox
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets-PyQt6/qfluentwidgets/components/widgets/combo_box.py", line 6, in <module>
    from .menu import RoundMenu
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets-PyQt6/qfluentwidgets/components/widgets/menu.py", line 2, in <module>
    from qframelesswindow import WindowEffect
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qframelesswindow/__init__.py", line 21, in <module>
    from .titlebar import TitleBar, TitleBarButton, SvgTitleBarButton, StandardTitleBar
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qframelesswindow/titlebar/__init__.py", line 8, in <module>
    from ..utils import startSystemMove
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qframelesswindow/utils/__init__.py", line 7, in <module>
    from .mac_utils import MacMoveResize as MoveResize
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qframelesswindow/utils/mac_utils.py", line 6, in <module>
    from PyQt5.QtCore import QT_VERSION_STR
ModuleNotFoundError: No module named 'PyQt5'
```
**复现**
`import qframelesswindow`

**疑似原因**
<img width="822" alt="image" src="https://user-images.githubusercontent.com/69903523/228595459-3e60ddf1-b75d-418c-a847-4c01947a7ed8.png">

图中
```python
from PyQt5.QtCore import QT_VERSION_STR
from PyQt5.QtWidgets import QWidget
```
改为
```python
from PyQt6.QtCore import QT_VERSION_STR
from PyQt6.QtWidgets import QWidget
```

即可解决问题

**Comment by zhiyiYo** [comment]
感谢反馈，目前已修复此问题
