### ISSUE TITLE
PySide6==6.5.0下MainWindow无法使用

### ISSUE THREAD

**Issue by TaoChenyue** [zhiyiYo/PyQt-Frameless-Window#73]
**Describe the bug**

**Environment**
 - OS: [e.g. Windows10]
 - DPI scaling: [e.g. 125%]
 - Python: [e.g. 3.8.6 64-bit]
 - PySide6: [e.g. 6.5.0]

**To Reproduce**
Steps to reproduce the behavior(you can use GIF to demonstrate :):
3. See error

**Code**
```sh
(PyQt-Fluent-Widgets) PS C:\Code\PyQt-Frameless-Window> pip list
Package                    Version
-------------------------- ---------
certifi                    2022.12.7
click                      8.1.3
colorama                   0.4.6
colorthief                 0.2.1
darkdetect                 0.8.0
numpy                      1.24.2
Pillow                     9.4.0
pip                        23.0.1
PySide6                    6.5.0
PySide6-Addons             6.5.0
PySide6-Essentials         6.5.0
PySide6-Fluent-Widgets     0.6.8
PySideSix-Frameless-Window 0.0.5
pywin32                    306
scipy                      1.10.1
setuptools                 65.6.3
shiboken6                  6.5.0
wheel                      0.38.4
wincertstore               0.2
(PyQt-Fluent-Widgets) PS C:\Code\PyQt-Frameless-Window> python .\examples\main_window.py
Traceback (most recent call last):
  File ".\examples\main_window.py", line 67, in <module>
    window = MainWindow()
  File ".\examples\main_window.py", line 13, in __init__
    super().__init__()
  File "C:\Scoop\apps\miniconda3\current\envs\PyQt-Fluent-Widgets\lib\site-packages\qframelesswindow\__init__.py", line 65, in __init__
    super().__init__(parent=parent)
RuntimeError: You can't initialize an PySide6.QtWidgets.QMainWindow object in class MainWindow twice!

```

**Expected behavior**

**Screenshots**

**Comment by TaoChenyue** [comment]
很奇怪，6.4.3没问题

**Comment by zhiyiYo** [comment]
创建一个新的虚拟环境试试？

**Comment by TaoChenyue** [comment]
一样的

**Comment by TaoChenyue** [comment]
只有```python .\examples\main_window.py```出问题，```python .\examples\demo.py```没问题

**Comment by zhiyiYo** [comment]
可能是pyside6多重继承的坑

**Comment by TaoChenyue** [comment]
这么写没错
```python
from PySide6.QtWidgets import *

class MainWindow(QMainWindow,QWidget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        
app=QApplication()
window=MainWindow()
window.show()
app.exec()
```
这样写就有错了
```python
from PySide6.QtWidgets import *

class Widget(QWidget):
    pass

class MainWindow(QMainWindow,Widget):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        
app=QApplication()
window=MainWindow()
window.show()
app.exec()
```

**Comment by zhiyiYo** [comment]
调换 `class FramelessMainWindow()` 里面的类顺序可以吗

**Comment by TaoChenyue** [comment]
换完不显示窗口

**Comment by v479038280** [comment]
同样的问题不知道解决了没有

**Comment by zhiyiYo** [comment]
先换回 6.4.2 吧

**Comment by TaoChenyue** [comment]
暂时没有，可以先用6.4.3的。我打算通过重构解决多继承问题。

**Comment by TaoChenyue** [comment]
@zhiyiYo 大佬能不能加个qtpy分支，我后续改完会提交，不影响现在的其他分支。

**Comment by zhiyiYo** [comment]
> 暂时没有，可以先用6.4.3的。我打算通过重构解决多继承问题。

我之后会解决，先别瞎搞

**Comment by zhiyiYo** [comment]
pyside 6.5.0 有点问题，最大化后窗口宽度会大于显示器，6.4.2 无此问题
